language: node_js

node_js:
  - '10'
  - '8'
  - '6'

before_install:
  - npm install -g npm@6.0.0

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  - npm run cover

after_success:
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - /^renovate\//
