language: node_js
node_js:
 - 'node'
 - '4'
env:
  matrix:
   - TS_VERSION=1
   - TS_VERSION=2
install:
 - npm install
 - npm install typescript@$TS_VERSION
 - typings install
script:
 - npm run lint
 - npm run build
 - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
